# Generated by Django 4.2.7 on 2024-02-11 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pupil', '0001_initial'),
        ('sengineer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_types', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=10)),
                ('appointment_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Running', 'Running')], default='Pending', max_length=10)),
                ('problemstat', models.TextField()),
                ('cancel', models.BooleanField(default=False)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sengineer.engineer')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupil.pupil')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sengineer.availabletime')),
            ],
        ),
    ]
